---
language: python
dist: focal
python: "3.9"
services:
  - docker

branches:
  only:
    - main

addons:
  apt:
    packages:
      - python3-pip
      - shellcheck

install:
  - pip install --upgrade pip
  - pip install -r ./.travis/requirements.txt
  - ansible --version

script:
  - ansible-lint ./
  - yamllint ./
  - shellcheck ./.travis/*.sh

after_script:
  - ./.travis/do-tests.sh

after_success:
  - ./.travis/version.sh
  - ./.travis/push-tags.sh

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    if: type = push
