---
- name: include regional vars
  include_vars:
    file: "{{ item }}.yml"
  loop:
    - use1
    - euc1
    - svc1
  when: inventory_hostname in groups[item]

- name: run bastion setup tasks
  include_tasks: setup.yml
  when:
    - bastion_node_role is defined
    - bastion_node_role == "bastion"

- name: run user bootstrap tasks
  include_tasks: users.yml
  when:
    - bastion_node_role is defined
    - bastion_node_role == "bastion"

- name: run target bootstrap tasks
  include_tasks: targets.yml
  when:
    - bastion_node_role is defined
    - bastion_node_role == "target"
