---
- name: gather group data
  getent:
    database: group

- name: ensure initial users exist on bastion
  become: no
  delegate_to: localhost
  command: "{{ bastion_ansible_ssh_command }} accountCreate --account {{ item.name }} --uid-auto --public-key {{ item.public_key }}"
  loop: "{{ bastion_initial_users }}"
  when: item.name not in getent_passwd.keys()
  tags:
    - bastion_users

- name: ensure initial groups exist on bastion
  become: no
  delegate_to: localhost
  command: "{{ bastion_ansible_ssh_command }} groupCreate --group {{ item.name }} --owner {{ item.owner }} --algo {{ item.algorithm | default('ed25519')}}"
  loop: "{{ bastion_initial_groups }}"
  # ovhbastion prefixes bastion groups with `key`
  when: "'key{{ item.name }}' not in getent_group.keys()"
  tags:
    - bastion_users

# disabled: need to define gatekeeper handling for groupAddMember plugin
- name: ensure users belong to expected groups
  become: no
  delegate_to: localhost
  command: "{{ bastion_ansible_ssh_command }} groupAddMember --account {{ item.0.name }} --group {{ item.1 }}"
  with_subelements:
    - "{{ bastion_initial_users }}"
    - groups
    - flags:
      skip_missing: true
  tags:
    - bastion_users
  when: false

# NOTE: `host` can be a CIDR range
# although this operation doesn't fail on repeated adds, it always reports as changed
- name: ensure users have host accesses installed
  become: no
  delegate_to: localhost
  command: "{{ bastion_ansible_ssh_command }} accountAddPersonalAccess --account {{ item.0.name }} --host {{ item.1 }}"
  with_subelements:
    - "{{ bastion_initial_users }}"
    - hosts
    - flags:
      skip_missing: true
  tags:
    - bastion_users

# disabled: need to define gatekeeper handling for groupAddMember plugin
- name: ensure groups have host accesses installed
  become: no
  delegate_to: localhost
  command: "{{ bastion_ansible_ssh_command }} groupAddServer --group {{ item.0.name }} --host {{ item.1.host }} --user {{ item.1.user }} --port {{ item.1.port | default(22) }} --force"
  with_subelements:
    - "{{ bastion_initial_groups }}"
    - hosts
    - flags:
      skip_missing: true
  tags:
    - bastion_users
  when: false

- name: save egress keys from users
  become: no
  delegate_to: localhost
  shell: "{{ bastion_ansible_ssh_command }} accountListEgressKeys --account {{ item.name }} --quiet | grep '^from='"
  with_items: "{{ bastion_initial_users }}"
  register: bastion_users_ssh_keys
  tags:
    - bastion_users

- name: create placeholder host
  add_host:
    name: bastion_fact_placeholder
    # this one is complicated: iterate over the list of users, pair them with
    # their public key, and then turn the list of lists into a dict, with
    # username as key, and public key as value
    user_key_map: "{{ dict(bastion_initial_users | map(attribute='name') | zip(bastion_users_ssh_keys.results | map(attribute='stdout'))) }}"
