---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include ansible-ovhbastion"
      include_role:
        name: "ansible-ovhbastion"
      vars:
        bastion_node_role: bastion
        ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRhS89ZWIBoQ5FZU2jSKRqQ4l38ghFmm2OCE/ZpmKUg daisy@daisy
        bastion_name: "test-bastion"
        bastion_superadmin_uname: ldelelis
        bastion_initial_groups:
          - name: test
            owner: ldelelis
            hosts:
              - host: rocket.chat
                user: random
                port: 2222
              - host: contoso.com
                user: root
              - host: 172.16.100.0/24
          - name: foo
            owner: ldelelis
        bastion_initial_users:
          - name: lucio.delelis
            public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRhS89ZWIBoQ5FZU2jSKRqQ4l38ghFmm2OCE/ZpmKUg daisy@daisy
            hosts:
              - rocket.chat
              - 172.16.100.0/24
          - name: someone.else
            public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRhS89ZWIBoQ5FZU2jSKRqQ4l38ghFmm2OCE/ZpmKUg daisy@daisy
            groups:
              - foo
