---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include ansible-ovhbastion"
      include_role:
        name: "ansible-ovhbastion"
      vars:
        ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRhS89ZWIBoQ5FZU2jSKRqQ4l38ghFmm2OCE/ZpmKUg daisy@daisy
        bastion_name: "test-bastion"
        bastion_superadmin_uname: ldelelis
        bastion_initial_groups:
          - name: test
            owner: lucio.delelis
            hosts:
              - host: rocket.chat
                user: random
                port: 2222
              - host: contoso.com
                user: root
          - name: foo
            owner: lucio.delelis
        bastion_initial_users:
          - name: lucio.delelis
            public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRhS89ZWIBoQ5FZU2jSKRqQ4l38ghFmm2OCE/ZpmKUg daisy@daisy
            hosts:
              - rocket.chat
          - name: someone.else
            public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRhS89ZWIBoQ5FZU2jSKRqQ4l38ghFmm2OCE/ZpmKUg daisy@daisy
            groups:
              - foo
